// ─── PLATFORMS ───────────────────────────────────────────────────────────────
const PLATFORMS = {
  // GRATIS/YOUTUBE
  itvx:          { name:'ITVX',                type:'Gratis (VPN UK)',       url:'https://www.itv.com' },
  redbulltv:     { name:'Red Bull TV',         type:'Gratis',                url:'https://www.redbull.com/int-en/discover' },
  servustv:      { name:'ServusTV',            type:'Gratis (VPN Austria)',   url:'https://www.servustv.com' },
  band:          { name:'Band',                type:'Gratis (VPN Brasil)',    url:'https://www.band.uol.com.br' },
  lequipe:       { name:"L'Equipe",            type:'Gratis (VPN Francia)',   url:'https://live.lequipe.fr' },
  somos_fox:     { name:'Somos Fox',           type:'Gratis (YouTube)',       url:'https://www.youtube.com/@somos_fox' },
  cwnetwork:     { name:'CW Network',          type:'Gratis (VPN EEUU)',      url:'https://www.cwtv.com' },
  srf:           { name:'SRF / RTS / RSI',     type:'Gratis (VPN Suiza)',     url:'https://www.srf.ch/play/tv' },
  rtbf:          { name:'RTBF',                type:'Gratis (VPN Bélgica)',   url:'https://auvio.rtbf.be' },
  orf:           { name:'ORF',                 type:'Gratis (VPN Austria)',   url:'https://tvthek.orf.at' },
  btcc_yt:       { name:'BTCC YouTube',        type:'Gratis (YouTube)',       url:'https://www.youtube.com/@OfficialBTCC' },
  itvsport_yt:   { name:'ITV Sport Extra',     type:'Gratis (YouTube)',       url:'https://www.youtube.com/@ITVSportExtra' },
  erx_yt:        { name:'FIA Rallycross YT',   type:'Gratis (YouTube)',       url:'https://www.youtube.com/@fiarallycross' },
  gtworld_yt:    { name:'GT World YouTube',    type:'Gratis (YouTube)',       url:'https://www.youtube.com/@GTWorld' },
  adac_yt:       { name:'ADAC YouTube',        type:'Gratis (YouTube)',       url:'http://youtube.com/@ADACMotorsports' },
  tcrtv_yt:      { name:'TCR TV YouTube',      type:'Gratis (YouTube)',       url:'https://www.youtube.com/@TCRTV' },
  dtm_yt:        { name:'DTM YouTube',         type:'Gratis (YouTube)',       url:'https://www.youtube.com/@DTM' },
  nurb_yt:       { name:'Nürburgring YouTube', type:'Gratis (YouTube)',       url:'https://www.youtube.com/@n%C3%BCrburgring_official' },
  f4ita_yt:      { name:'Italian F4 YouTube',  type:'Gratis (YouTube)',       url:'https://www.youtube.com/@Italianf4-Euro4' },
  imsatv:        { name:'IMSA.tv',             type:'Gratis',                url:'https://www.imsa.com/tvlive' },
  elms_yt:       { name:'ELMS YouTube',        type:'Gratis (YouTube)',       url:'https://www.youtube.com/@EuropeanLeMansSeries' },
  alms_yt:       { name:'ALMS YouTube',        type:'Gratis (YouTube)',       url:'https://www.youtube.com/@AsianLeMansSeries' },
  stockcar_yt:   { name:'Stock Car YouTube',   type:'Gratis (YouTube)',       url:'https://www.youtube.com/@stockcarchannel' },
  speedtour_tv:  { name:'Speed Tour TV',       type:'Gratis (YouTube)',       url:'https://www.youtube.com/@SpeedTourTV' },
  rtve:          { name:'RTVE / Teledeporte',  type:'Gratis (VPN España)',    url:'https://www.rtve.es/play/deportes' },
  fdrift_yt:     { name:'Formula Drift YT',    type:'Gratis (YouTube)',       url:'https://www.youtube.com/@FormulaDrift' },
  driftm_yt:     { name:'Drift Masters YT',    type:'Gratis (YouTube)',       url:'https://www.youtube.com/@DriftMastersGrandPrix' },

  btrc_yt:       { name:'BTRC YouTube',        type:'Gratis (YouTube)',       url:'https://www.youtube.com/@OfficialTruckSportUK' },
  tiktok:        { name:'TikTok',              type:'Gratis',                url:'https://www.tiktok.com' },
  rande:         { name:'ran.de / ProSieben',  type:'Gratis (VPN Alemania)',  url:'https://www.ran.de' },
  abema:         { name:'Abema',               type:'Gratis (VPN Japón)',     url:'https://abema.tv' },
  motorsporttv_f:{ name:'Motorsport.tv',       type:'Gratis',                url:'https://motorsport.tv' },
  tycsports_g:   { name:'TyC Sports',          type:'Gratis',                url:null },
  elnueve_g:     { name:'El Nueve',            type:'Gratis',                url:null },

  // PIRATAS
  acestrlms:     { name:'Acestrlms',           type:'Pirata',                url:'https://acestrlms.pages.dev/' },
  rbtv77:        { name:'RBTV77',              type:'Pirata',                url:null },
  pitsport:      { name:'PitSport',            type:'Pirata',                url:'https://pitsport.xyz/schedule' },

  // PAGOS — Oficiales Motorsport
  rallytv_m:     { name:'Rally.tv Mensual',           type:'Pago', price:12.99,    cur:'EUR', url:'https://www.rally.tv' },
  rallytv_a:     { name:'Rally.tv Anual',             type:'Pago', price:119.99,   cur:'EUR', url:'https://www.rally.tv' },
  rallytv_m_jp:  { name:'Rally.tv Mensual (Japan)',   type:'Pago', price:1500,     cur:'JPY', url:'https://www.rally.tv' },
  rallytv_a_jp:  { name:'Rally.tv Anual (Japan)',     type:'Pago', price:14000,    cur:'JPY', url:'https://www.rally.tv' },
  f1tv_m:        { name:'F1TV Pro Mensual',           type:'Pago', price:7.99,     cur:'USD', url:'https://f1tv.formula1.com' },
  f1tv_a:        { name:'F1TV Pro Anual',             type:'Pago', price:69.99,    cur:'USD', url:'https://f1tv.formula1.com' },
  fiawec_r:      { name:'FIAWEC.TV (1 Carrera)',      type:'Pago', price:8.99,     cur:'EUR', url:'https://fiawec.tv' },
  fiawec_s:      { name:'FIAWEC.TV (Temporada)',      type:'Pago', price:49.99,    cur:'EUR', url:'https://fiawec.tv' },
  fiawec_le:     { name:'FIAWEC.TV (24h Le Mans)',    type:'Pago', price:17.99,    cur:'EUR', url:'https://fiawec.tv' },
  vp_moto_s:     { name:'VideoPass MotoGP (Temp.)',   type:'Pago', price:148.99,   cur:'EUR', url:'https://www.motogp.com/en/videopass' },
  vp_moto_t:     { name:'VideoPass MotoGP + Timing', type:'Pago', price:157.99,   cur:'EUR', url:'https://www.motogp.com/en/videopass' },
  vp_sbk:        { name:'VideoPass WorldSBK',         type:'Pago', price:69.99,    cur:'EUR', url:'https://www.worldsbk.com/en/videopass' },
  msptv_m:       { name:'Motorsport.tv Mensual',      type:'Pago', price:5.99,     cur:'USD', url:'https://motorsport.tv' },
  msptv_a:       { name:'Motorsport.tv Anual',        type:'Pago', price:49.99,    cur:'USD', url:'https://motorsport.tv' },
  floracing:     { name:'FloRacing (Anual)',           type:'Pago', price:150.00,   cur:'USD', url:'https://www.floracing.com' },
  indycar_m:     { name:'IndyCar Live Mensual',       type:'Pago', price:5.99,     cur:'USD', url:'https://www.indycarlive.com' },
  indycar_s:     { name:'IndyCar Live Temporada',     type:'Pago', price:29.99,    cur:'USD', url:'https://www.indycarlive.com' },
  sfgo_m:        { name:'SFGO Mensual',               type:'Pago', price:1480,     cur:'JPY', url:'https://sfgo.jp' },
  sfgo_a:        { name:'SFGO Anual',                 type:'Pago', price:11880,    cur:'JPY', url:'https://sfgo.jp' },
  superview:     { name:'SuperView Temporada',        type:'Pago', price:60.00,    cur:'AUD', url:'https://www.supercars.com/superview' },
  supercars_yt:  { name:'Supercars YT Membresía',     type:'Pago', price:150,      cur:'ARS', url:'https://www.youtube.com/@supercars' },
  ttplus:        { name:'TT+ (Live Pass)',            type:'Pago', price:14.99,    cur:'GBP', url:'https://ttplus.iomttraces.com' },
  tcrtv_vip:     { name:'TCR TV VIP (Temporada)',     type:'Pago', price:30.00,    cur:'EUR', url:'https://tcr-series.tv' },
  rx_plus:       { name:'RX+',                        type:'Pago', price:9.99,     cur:'EUR', url:'https://rxplus.tv' },
  motorplay:     { name:'Motorplay',           type:'Pago', price:6900,      cur:'ARS', url:'https://motorplay.tv/' },

  // PAGOS — Streaming General
  dp_std:        { name:'Disney+ Estándar',           type:'Pago', price:19834,    cur:'ARS', url:'https://www.disneyplus.com' },
  dp_prem:       { name:'Disney+ Premium',            type:'Pago', price:19834,    cur:'ARS', url:'https://www.disneyplus.com' },
  max_basic:     { name:'Max Basic (con anuncios)',    type:'Pago', price:10.99,    cur:'USD', url:'https://www.max.com' },
  max_std:       { name:'Max Standard',               type:'Pago', price:18.49,    cur:'USD', url:'https://www.max.com' },
  max_prem:      { name:'Max Premium (4K)',            type:'Pago', price:22.99,    cur:'USD', url:'https://www.max.com' },
  peacock_s:     { name:'Peacock Select',             type:'Pago', price:7.99,     cur:'USD', url:'https://www.peacocktv.com' },
  peacock_p:     { name:'Peacock Premium',            type:'Pago', price:10.99,    cur:'USD', url:'https://www.peacocktv.com' },
  peacock_pp:    { name:'Peacock Premium Plus',       type:'Pago', price:16.99,    cur:'USD', url:'https://www.peacocktv.com' },
  espnplus:      { name:'ESPN+',                      type:'Pago', price:10.99,    cur:'USD', url:'https://plus.espn.com' },
  viaplay:       { name:'Viaplay',                    type:'Pago', price:15.99,    cur:'EUR', url:'https://viaplay.com' },
  dazn_motor:    { name:'DAZN Motor',                 type:'Pago', price:19.99,    cur:'EUR', url:'https://www.dazn.com' },
  dazn_full:     { name:'DAZN Esencial',              type:'Pago', price:29.99,    cur:'EUR', url:'https://www.dazn.com' },
  tntsports:     { name:'TNT Sports UK',              type:'Pago', price:30.99,    cur:'GBP', url:'https://www.tntsports.co.uk' },
  kayo_std:      { name:'Kayo Sports Standard',       type:'Pago', price:29.99,    cur:'AUD', url:'https://kayosports.com.au' },
  kayo_prem:     { name:'Kayo Sports Premium',        type:'Pago', price:45.99,    cur:'AUD', url:'https://kayosports.com.au' },
  stan_basic:    { name:'Stan Sport Basic',           type:'Pago', price:32.00,    cur:'AUD', url:'https://www.stan.com.au/sport' },
  stan_std:      { name:'Stan Sport Standard',        type:'Pago', price:37.00,    cur:'AUD', url:'https://www.stan.com.au/sport' },
  stan_prem:     { name:'Stan Sport Premium',         type:'Pago', price:42.00,    cur:'AUD', url:'https://www.stan.com.au/sport' },
  skysports:     { name:'Sky Sports UK',              type:'Pago', price:34.99,    cur:'GBP', url:'https://www.skysports.com' },
  skynz:         { name:'Sky Sport NZ',               type:'Pago', price:49.99,    cur:'NZD', url:'https://www.sky.co.nz' },
  globoplay:     { name:'Globoplay + Canales',        type:'Pago', price:54.90,    cur:'BRL', url:'https://globoplay.globo.com' },
  canalplus:     { name:'Canal+ Sport Francia',       type:'Pago', price:29.99,    cur:'EUR', url:'https://www.canalplus.com' },
  jsports:       { name:'J Sports Motor Pack',        type:'Pago', price:1980,     cur:'JPY', url:'https://jod.jsports.co.jp' },
  sling:         { name:'Sling TV Blue',              type:'Pago', price:40.00,    cur:'USD', url:'https://www.sling.com' },
  youtubetv:     { name:'YouTube TV',                 type:'Pago', price:72.99,    cur:'USD', url:'https://tv.youtube.com' },
  espn_ar:       { name:'ESPN (Cable)',               type:'Pago', price:0,        cur:'ARS', url:'https://www.espn.com.ar' },
  hulu_live:     { name:'Hulu + Live TV',             type:'Pago (VPN EEUU)', price:82.99,    cur:'USD', url:'https://www.hulu.com/live-tv' },
  fubotv:        { name:'FuboTV',                     type:'Pago (VPN EEUU)', price:84.99,    cur:'USD', url:'https://www.fubo.tv' },
  tsn:           { name:'TSN / TSN+ (Canadá)',        type:'Pago (VPN Canadá)', price:29.99,    cur:'CAD', url:'https://www.tsn.ca' },
  skysport_de:   { name:'Sky Sport Germany',          type:'Pago (VPN Alemania)', price:25.00,    cur:'EUR', url:'https://www.sky.de/sport' },
  skysport_it:   { name:'Sky Sport Italia',           type:'Pago (VPN Italia)', price:20.00,    cur:'EUR', url:'https://sport.sky.it' },
  motorvision_p: { name:'Motorvision+',               type:'Pago (VPN Alemania)', price:4.99,     cur:'EUR', url:'https://motorvision.tv' },
  movistar_p:    { name:'Movistar+ (España)',         type:'Pago (VPN España)', price:30.00,    cur:'EUR', url:'https://www.movistar.es' },
  ziggo_sport:   { name:'Ziggo Sport (Holanda)',      type:'Pago (VPN Países Bajos)', price:16.95,    cur:'EUR', url:'https://www.ziggosport.nl' },
  gaora:         { name:'Gaora (Japón)',              type:'Pago (VPN Japón)', price:1500,     cur:'JPY', url:'https://www.gaora.co.jp' },
  sporttv_pt:    { name:'Sport TV (Portugal)',        type:'Pago (VPN Portugal)', price:10.00,    cur:'EUR', url:'https://www.sporttv.pt' },
  voosport:      { name:'Voo Sport (Bélgica)',        type:'Pago (VPN Bélgica)', price:15.00,    cur:'EUR', url:'https://www.voosport.be' },
  ssport:        { name:'S Sport',                    type:'Pago (VPN)', price:0,        cur:'USD', url:'https://www.ssportplus.com' },
  network4:      { name:'Network 4 (Hungría)',        type:'Pago (VPN Hungría)', price:0,        cur:'HUF', url:'https://net4.network4.hu' },
  tvcultura:     { name:'TV Cultura',                 type:'Gratis (VPN Brasil)', url:'https://cultura.uol.com.br' },
  ninenetwork:   { name:'Nine Network (9Now)',        type:'Gratis (VPN Australia)', url:'https://www.9now.com.au' },
};

// ─── CATEGORIES ──────────────────────────────────────────────────────────────
const CATEGORIES = [
  { id:'wrc',         name:'WRC',               group:'Rally',
    platforms:['rallytv_m','rallytv_a','rallytv_m_jp','rallytv_a_jp','itvx','servustv','acestrlms','rbtv77','pitsport'] },
  { id:'erx',         name:'World RX',           group:'Rally',
    platforms:['erx_yt','rx_plus','rallytv_m','rallytv_a','acestrlms','rbtv77'] },

  { id:'f1',          name:'Formula 1',          group:'Fórmula',
    platforms:['dp_std','dp_prem','f1tv_m','f1tv_a','skysports','canalplus','espnplus','viaplay','srf','rtbf','servustv','orf','band','acestrlms','rbtv77','pitsport'] },
  { id:'f2',          name:'Formula 2',          group:'Fórmula',
    platforms:['dp_std','dp_prem','f1tv_m','f1tv_a','skysports','canalplus','espnplus','viaplay','srf','rtbf','servustv','orf','band','acestrlms','rbtv77','pitsport'] },
  { id:'f3',          name:'Formula 3',          group:'Fórmula',
    platforms:['dp_std','dp_prem','f1tv_m','f1tv_a','skysports','canalplus','espnplus','viaplay','srf','rtbf','servustv','orf','band','acestrlms','rbtv77','pitsport'] },
  { id:'f4ita',       name:'Italian F4',         group:'Fórmula',
    platforms:['f4ita_yt','motorsporttv_f','acestrlms','rbtv77'] },
  { id:'indynxt',     name:'IndyNXT',            group:'Fórmula',
    platforms:['indycar_m','indycar_s','peacock_p','acestrlms','rbtv77','pitsport'] },
  { id:'superf',      name:'Super Formula',      group:'Fórmula',
    platforms:['sfgo_m','sfgo_a','msptv_m','abema','jsports','acestrlms','rbtv77'] },
  { id:'indycar',     name:'IndyCar',            group:'Fórmula',
    platforms:['dp_prem','espn_ar','indycar_s','peacock_p','youtubetv','sling','hulu_live','fubotv','tsn','skysports','skysport_de','skysport_it','motorvision_p','movistar_p','viaplay','ziggo_sport','canalplus','gaora','sporttv_pt','stan_basic','skynz','voosport','ssport','network4','tvcultura','ninenetwork','acestrlms','rbtv77','pitsport'] },
  { id:'f2arg',       name:'Formula 2 Argentina', group:'Fórmula',
    platforms:['tycsports_g'] },
  { id:'f3arg',       name:'Formula 3 Argentina', group:'Fórmula',
    platforms:['tycsports_g'] },
  { id:'fnac',        name:'Formula Nacional',   group:'Fórmula',
    platforms:['tycsports_g'] },

  { id:'wec',         name:'WEC',                group:'Resistencia',
    platforms:['max_std','fiawec_r','fiawec_s','fiawec_le','tntsports','band','lequipe','somos_fox','acestrlms','rbtv77'] },
  { id:'imsa',        name:'IMSA',               group:'Resistencia',
    platforms:['imsatv','peacock_p','peacock_pp','acestrlms','rbtv77','pitsport'] },
  { id:'elms',        name:'ELMS',               group:'Resistencia',
    platforms:['elms_yt','motorsporttv_f','acestrlms','rbtv77'] },
  { id:'alms',        name:'ALMS',               group:'Resistencia',
    platforms:['alms_yt','motorsporttv_f','acestrlms','rbtv77'] },
  { id:'nls',         name:'NLS / N24',           group:'Resistencia',
    platforms:['nurb_yt','acestrlms','rbtv77'] },
  { id:'ewc',         name:'FIM EWC',             group:'Resistencia',
    platforms:['max_std','jsports','acestrlms','rbtv77'] },

  { id:'gulf12',      name:'Gulf 12 Hours',       group:'Resistencia',
    platforms:['gtworld_yt','motorsporttv_f','acestrlms','rbtv77'] },

  { id:'motogp',      name:'MotoGP',             group:'Motos',
    platforms:['dp_std','dp_prem','vp_moto_s','vp_moto_t','tntsports','dazn_motor','skysports','canalplus','servustv','max_std','rtbf','srf','acestrlms','rbtv77','pitsport'] },
  { id:'moto2',       name:'Moto2',              group:'Motos',
    platforms:['dp_std','dp_prem','vp_moto_s','vp_moto_t','tntsports','dazn_motor','skysports','canalplus','servustv','max_std','rtbf','srf','acestrlms','rbtv77','pitsport'] },
  { id:'moto3',       name:'Moto3',              group:'Motos',
    platforms:['dp_std','dp_prem','vp_moto_s','vp_moto_t','tntsports','dazn_motor','skysports','canalplus','servustv','max_std','rtbf','srf','acestrlms','rbtv77','pitsport'] },
  { id:'wsbk',        name:'World SBK',          group:'Motos',
    platforms:['dp_std','dp_prem','vp_sbk','tntsports','rtve','servustv','acestrlms','rbtv77'] },
  { id:'iomtt',       name:'Isle of Man TT',      group:'Motos',
    platforms:['ttplus','itvx','acestrlms','rbtv77'] },

  { id:'gtworld',     name:'GT World Tour',       group:'GTs',
    platforms:['gtworld_yt','skysports','kayo_std','jsports','rtbf','acestrlms','rbtv77'] },
  { id:'gtwce',       name:'GTWC Europe',         group:'GTs',
    platforms:['gtworld_yt','skysports','motorsporttv_f','rtbf','acestrlms','rbtv77'] },
  { id:'gtwca',       name:'GTWC America',        group:'GTs',
    platforms:['gtworld_yt','max_std','motorsporttv_f','acestrlms','rbtv77'] },
  { id:'adac',        name:'ADAC GT Masters',     group:'GTs',
    platforms:['adac_yt','rande','servustv','acestrlms','rbtv77'] },
  { id:'dtm',         name:'DTM',                group:'GTs',
    platforms:['dtm_yt','rande','servustv','viaplay','msptv_m','acestrlms','rbtv77'] },

  { id:'nascar_cup',  name:'NASCAR Cup',         group:'Stock Cars',
    platforms:['sling','youtubetv','tntsports','band','somos_fox','acestrlms','rbtv77','pitsport'] },
  { id:'nascar_truck',name:'NASCAR Truck',        group:'Stock Cars',
    platforms:['sling','youtubetv','floracing','somos_fox','acestrlms','rbtv77','pitsport'] },
  { id:'nascar_or',   name:"NASCAR O'Reilly",     group:'Stock Cars',
    platforms:['cwnetwork','somos_fox','acestrlms','rbtv77','pitsport'] },
  { id:'arca',        name:'ARCA Menards',        group:'Stock Cars',
    platforms:['floracing','sling','youtubetv','acestrlms','rbtv77'] },
  { id:'stock',       name:'Stock Car Brasil',    group:'Stock Cars',
    platforms:['stockcar_yt','globoplay','band','acestrlms','rbtv77'] },
  { id:'tc',          name:'TC',                 group:'Stock Cars',
    platforms:['elnueve_g','motorplay'] },
  { id:'tcp',         name:'TC Pista',           group:'Stock Cars',
    platforms:['elnueve_g','motorplay'] },
  { id:'tcm',         name:'TC Mouras',          group:'Stock Cars',
    platforms:['elnueve_g','motorplay'] },
  { id:'tcpm',        name:'TC Pista Mouras',    group:'Stock Cars',
    platforms:['elnueve_g','motorplay'] },
  { id:'tcpk',        name:'TC Pick Up',         group:'Stock Cars',
    platforms:['elnueve_g','motorplay'] },
  { id:'tcppk',       name:'TC Pista Pick Up',   group:'Stock Cars',
    platforms:['elnueve_g','motorplay'] },
  { id:'tn',          name:'Turismo Nacional',   group:'Stock Cars',
    platforms:['elnueve_g','motorplay'] },
  { id:'tp',          name:'Turismo Pista',      group:'Stock Cars',
    platforms:['elnueve_g','motorplay'] },
  { id:'procar',      name:'Procar 4000',        group:'Stock Cars',
    platforms:['tycsports_g'] },
  { id:'toprace',     name:'Top Race',           group:'Stock Cars',
    platforms:['tycsports_g'] },

  { id:'supercars',   name:'Supercars',          group:'Touring Cars',
    platforms:['superview','supercars_yt','kayo_std','kayo_prem','skynz','tntsports','acestrlms','rbtv77'] },
  { id:'btcc',        name:'BTCC',               group:'Touring Cars',
    platforms:['btcc_yt','itvsport_yt','itvx','tiktok','msptv_m','acestrlms','rbtv77'] },
  { id:'tc2000',      name:'TC2000',             group:'Touring Cars',
    platforms:['tycsports_g'] },
  { id:'fiat',        name:'Fiat Competizione',  group:'Touring Cars',
    platforms:['tycsports_g'] },
  { id:'tcr_world',   name:'TCR World Tour',      group:'Touring Cars',
    platforms:['tcrtv_yt','tcrtv_vip','acestrlms','rbtv77'] },
  { id:'tcr_eu',      name:'TCR Europe',          group:'Touring Cars',
    platforms:['tcrtv_yt','tcrtv_vip','acestrlms','rbtv77'] },
  { id:'tcr_am',      name:'TCR America',         group:'Touring Cars',
    platforms:['tcrtv_yt','motorsporttv_f','speedtour_tv','acestrlms','rbtv77'] },
  { id:'btrc',        name:'British Truck Racing', group:'Touring Cars',
    platforms:['btrc_yt','motorsporttv_f','tiktok','acestrlms','rbtv77'] },

  { id:'fdrift',      name:'Formula Drift',       group:'Drift',
    platforms:['fdrift_yt','floracing','acestrlms','rbtv77'] },
  { id:'driftm',      name:'Drift Masters',       group:'Drift',
    platforms:['driftm_yt','redbulltv','acestrlms','rbtv77'] },
];
